#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#
#server:
#  port: 0
#
#spring:
#  application:
#    name: product-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/productservice?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
#    username: root
#    password: root
#
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        use_sql_comments: true
#        format_sql: true
#
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0